# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
a=np.random.randn(3,3,3)
print(a)

[[[-0.34653484  0.56897605 -1.77853107]
  [-0.35113546 -0.46475589 -0.24057411]
  [ 0.79049567  0.45713229  1.07369907]]

 [[ 0.90460496 -0.53800902 -0.62247334]
  [ 1.67903003 -0.81029304 -2.11041058]
  [ 1.35664148  0.21906458  1.22873732]]

 [[-0.12727153  0.44960546  0.40022005]
  [ 1.15373364  0.2885949  -0.58193909]
  [ 0.82411912  0.10464631 -0.88980385]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [14]:
a=np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if((i+j)%2):
            a[i][j]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [35]:
a=np.random.randn(5,5)
(a-a.mean())/(np.amax(a)-np.amin(a))


array([[ 0.11690297,  0.19150301,  0.33825399, -0.38663835,  0.07535238],
       [ 0.00424938, -0.10361833,  0.103783  , -0.18359064, -0.38357814],
       [ 0.43071349,  0.04342899, -0.1399474 , -0.23236893, -0.56928651],
       [ 0.03154454,  0.2471398 ,  0.25880108,  0.22156205,  0.25269581],
       [-0.27579369,  0.0452233 , -0.11205262, -0.17849738,  0.2042182 ]])

# 5.  How to find common values between two arrays?

In [37]:
a=np.random.randn(5,5)
b=np.random.randn(5,5)
c= (a==b)
print(c*a)

[[ 0. -0. -0.  0.  0.]
 [ 0.  0. -0. -0. -0.]
 [-0. -0.  0.  0. -0.]
 [-0. -0. -0. -0.  0.]
 [-0. -0.  0.  0. -0.]]


# 6.How to get the dates of yesterday, today and tomorrow?

In [44]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestreday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [6]:
a=np.random.rand(3,3)
b=np.random.rand(3,3)
print(np.sum(a==b)!=0)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [54]:
a=np.random.rand(10)
a[a.argmax()]=0
a

array([0.77816789, 0.40968808, 0.59292448, 0.51028852, 0.74978224,
       0.32893287, 0.23890559, 0.53598289, 0.41936271, 0.        ])

# 9. How to print all the values of an array?

In [55]:
a=np.random.rand(5,5)
print(a)

[[0.60850478 0.18499896 0.67578823 0.70390339 0.77530867]
 [0.56929406 0.97993419 0.5772302  0.96230009 0.32448088]
 [0.58662629 0.18925226 0.92459494 0.61117483 0.52126328]
 [0.28568759 0.12574671 0.2573506  0.96769639 0.3673405 ]
 [0.66177224 0.18387653 0.84714989 0.67353418 0.53236908]]


# 10.Subtract the mean of each row of a matrix

In [71]:
a=np.arange(6).reshape(2,3)
n=a.mean(axis=1,keepdims=True)
a=a-n
a

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [75]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
Z

array([2., 4., 2., 5., 5., 2., 2., 4., 2., 2.])

# 12.How to get the diagonal of a dot product?

In [78]:
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)
np.trace(a*b)

40

# 13.How to find the most frequent value in an array?

In [87]:
a=np.arange(6).reshape(2,3)
#a=np.random.randint(0, 10, 40)
print(np.bincount(a).argmax())

ValueError: object too deep for desired array

# 14.How to get the n largest values of an array

In [97]:
n=4
a=np.random.randint(0, 10, (8,8))
b=np.unique(a)
list(b[-n:])

[6, 7, 8, 9]

# 15.How to create a record array from a regular array?

In [98]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
